// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnaxdrwqmvzixyrmcsbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYXhkcndxbXZ6aXh5cm1jc2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTAzMDQsImV4cCI6MjA2ODI2NjMwNH0.uax_PvQDw9WETyom943jWTKfQa5w3nR6q-6ABbKJ1lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});